language: node_js
node_js:
  - "10"
env:
  global:
    - GH_PAGES_SRC="packages/apps/build"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn polkadot-dev-travis-build
deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  provider: script
  script: ./scripts/deploy-gh-page.sh
  on:
    branch: master
